// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddreferralController from "./addreferral_controller"
application.register("addreferral", AddreferralController)

import AmazonSearchProductsController from "./amazon_search_products_controller"
application.register("amazon-search-products", AmazonSearchProductsController)

import AvatarPreviewController from "./avatar_preview_controller"
application.register("avatar-preview", AvatarPreviewController)

import BookmarksController from "./bookmarks_controller"
application.register("bookmarks", BookmarksController)

import CommentsController from "./comments_controller"
application.register("comments", CommentsController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import FormValidationController from "./form_validation_controller"
application.register("form-validation", FormValidationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import RepliesAndCommentsController from "./replies_and_comments_controller"
application.register("replies-and-comments", RepliesAndCommentsController)

import RepliesController from "./replies_controller"
application.register("replies", RepliesController)
