// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookmarksController from "./bookmarks_controller"
application.register("bookmarks", BookmarksController)

import CommentsController from "./comments_controller"
application.register("comments", CommentsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RepliesAndCommentsController from "./replies_and_comments_controller"
application.register("replies-and-comments", RepliesAndCommentsController)

import RepliesController from "./replies_controller"
application.register("replies", RepliesController)
