// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddreferralController from "./addreferral_controller"
application.register("addreferral", AddreferralController)

import AmazonSearchProductsController from "./amazon_search_products_controller"
application.register("amazon-search-products", AmazonSearchProductsController)

import AvatarPreviewController from "./avatar_preview_controller"
application.register("avatar-preview", AvatarPreviewController)

import BookmarksController from "./bookmarks_controller"
application.register("bookmarks", BookmarksController)

import CharactercounterController from "./charactercounter_controller"
application.register("charactercounter", CharactercounterController)

import CommentsController from "./comments_controller"
application.register("comments", CommentsController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import FollowsController from "./follows_controller"
application.register("follows", FollowsController)

import FormValidationController from "./form_validation_controller"
application.register("form-validation", FormValidationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HidemodalController from "./hidemodal_controller"
application.register("hidemodal", HidemodalController)

import ListPaginationController from "./list_pagination_controller"
application.register("list-pagination", ListPaginationController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import PaginationController from "./pagination_controller"
application.register("pagination", PaginationController)

import ProductPaginationController from "./product_pagination_controller"
application.register("product-pagination", ProductPaginationController)

import ReferralPaginationController from "./referral_pagination_controller"
application.register("referral-pagination", ReferralPaginationController)

import RepliesAndCommentsController from "./replies_and_comments_controller"
application.register("replies-and-comments", RepliesAndCommentsController)

import RepliesController from "./replies_controller"
application.register("replies", RepliesController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SlidingimagerowsController from "./slidingimagerows_controller"
application.register("slidingimagerows", SlidingimagerowsController)

import UserPaginationController from "./user_pagination_controller"
application.register("user-pagination", UserPaginationController)
