development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_TLS_URL") { ENV.fetch("REDIS_URL") } %>
  channel_prefix: Favolist_4_0_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>

